### ISSUE TITLE
Failed to get authorization code. Bad TOTP Key?

### ISSUE THREAD

**Issue by mercertom** [BigThunderSR/OnStarJS#224]
I know I copied the secret correctly from the QR code, I tried replacing it with capital letters where it was lowercase, to no avail. Tried a new v4 uuid, same error. Any ideas? It worked on gm website w mobile authenticator app, so I don't think it's actually a failure with the TOTP key.

**Comment by mercertom** [comment]
[00:19:04] INFO: Starting OnStar2MQTT for Vehicle1...
> onstar2mqtt@1.20.1 start
> node src/index.js
info: OnStar Config: {"onstarConfig":{"allowCommands":true,"checkRequestStatus":true,"deviceId":"10da774f-4dea-4d11-8b1d-a83c9902b7e5","onStarPin":"####","onStarTOTP":"***************","password":"********","refreshInterval":1800000,"requestPollingIntervalSeconds":6,"requestPollingTimeoutSeconds":90,"tokenLocation":"","username":"***********","vin":"realVINhere"},"timestamp":"2024-12-24 00:19:08"}
info: MQTT Config: {"mqttConfig":{"host":"myhomeassistant:1883","listAllSensorsTogether":false,"namePrefix":"","password":"********","pollingStatusTopic":"","port":1883,"prefix":"homeassistant","rejectUnauthorized":true,"tls":false,"username":"mqtt-user"},"timestamp":"2024-12-24 00:19:08"}
info: !-- Starting OnStar2MQTT Polling --! {"timestamp":"2024-12-24 00:19:08"}
info: Requesting vehicles {"timestamp":"2024-12-24 00:19:08"}
Authentication failed: Error: Failed to get authorization code. Bad TOTP Key?
    at GMAuth.<anonymous> (/app/node_modules/onstarjs2/dist/index.cjs:40614:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/onstarjs2/dist/index.cjs:43:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
error: Main function error: {"error":{"message":"Failed to get authorization code. Bad TOTP Key?"},"timestamp":"2024-12-24 00:19:15"}
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started

**Comment by mercertom** [comment]
16. It passed the checks that made the configuration accept it. As either lower case as it originally came, or capitalized letters.

**Comment by mercertom** [comment]
I believe my system time is broken. Trying to find the way to set it back to the truth.

**Comment by mercertom** [comment]
Do you know how to (re)set HA system time? I've just read about 20 search results, and gotten nowhere.

**Comment by mercertom** [comment]
Restarted, was 30s wrong, got a different error. Installed chrony add-on, now need to figure out hostname for MQTT. What do you recommend to set for that? It's all set up with Mosquitto, but localhost and the hostname for my HA didn't work.

**Comment by mercertom** [comment]
It works, had to change hostname to "core-mosquitto".

**Comment by mercertom** [comment]
Install chronyd add-on to sync system time to real time. This is always an issue with TOTP 2FA.

**Comment by ehran** [comment]
Following this thread - having the same error
